/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sata' at '10/11/15 4:45 PM' with Gradle 2.7
 *
 * @author sata, @date 10/11/15 4:45 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
